name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nix:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - uses: wprhvso/qa-nix@v1
        with:
          checks: fmt,statix,deadnix,flake

  shell:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - uses: wprhvso/qa-shell@v1
