name: ci

on:
  push:

jobs:
  nixfmt:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: git ls-files '*.nix' | xargs nixfmt --check

  statix:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: statix check

  deadnix:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: git ls-files '*.nix' | xargs deadnix --fail --no-lambda-pattern-names --no-underscore

  flake:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: nix flake check -L

  shellcheck:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: shellcheck --exclude=SC1091,SC2029 nix-bot-config.sh

  shfmt:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: shfmt -i 4 -ci --diff nix-bot-config.sh
